# Generated by Django 4.2 on 2024-06-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_api', '0004_fileupload_email_fileupload_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='last_name',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
