# Generated by Django 4.2 on 2024-06-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_api', '0005_remove_fileupload_email_remove_fileupload_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='data',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
